[features]
seeds = false
skip-lint = false
[programs.localnet]
multi_chain_amm = "8mD7hwb1rqXnhCLq67RT4KHg1H93hiWekjHjvy7z6Q3U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/nick/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
